#!/usr/bin/env python3
"""
payload_flight_simulation_visual.py
Cinematic BACAR-13 visual that closely matches the user's reference image.
- Left: large cinematic 3D area with vertical rod, past/future dots, lilac cube with shading
- Right: embedded chart image generated by src/plotter/mpu6050_plotter.py -> charts/mpu_chart.svg (if present)
- Exports FullHD MP4, exact one-frame-per-telemetry-row mapping
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.animation import FFMpegWriter
from mpl_toolkits.mplot3d import art3d
from mpl_toolkits.mplot3d.art3d import Poly3DCollection, Line3DCollection
from scipy.spatial.transform import Rotation as R
from scipy.signal import savgol_filter
from PIL import Image
import warnings

# ---------------- CONFIG ----------------
PROJECT_ROOT = os.path.dirname(os.path.dirname(__file__))
DATA_FILE = os.path.join(PROJECT_ROOT, "src", "logger", "data", "MPU6050.txt")
CHART_SVG = os.path.join(PROJECT_ROOT, "src", "plotter", "charts", "mpu_chart.svg")
OUT_DIR = os.path.join(PROJECT_ROOT, "src", "output")
OUT_FILE = os.path.join(OUT_DIR, "BACAR13_full_simulation_vis.mp4")

FRAME_WIDTH = 1920
FRAME_HEIGHT = 1080
DPI = 150
CODEC = "libx264"

CUBE_COLOR_HEX = "#C8B9FF"  # pale lilac from your concept
CUBE_BASE = np.array([200/255., 185/255., 1.0])  # approximate RGB
CUBE_SIZE = 0.14
ACC_SCALE = 0.015
TRAIL_LENGTH = 80

SMOOTH_WINDOW = 51
SMOOTH_POLYORDER = 3

os.makedirs(OUT_DIR, exist_ok=True)

# ---------------- LOAD & PREP DATA ----------------
if not os.path.exists(DATA_FILE):
    raise FileNotFoundError(f"MPU6050 file not found: {DATA_FILE}")

df = pd.read_csv(DATA_FILE, comment="#")
if "timestamp" not in df.columns:
    raise ValueError("MPU6050.txt must contain 'timestamp' column")

df["timestamp"] = pd.to_datetime(df["timestamp"], errors="coerce")
df = df.dropna(subset=["timestamp"]).reset_index(drop=True)

for c in ("velocity_m_s","accel_x_m_s2","accel_y_m_s2","accel_z_m_s2",
          "gyro_x_dps","gyro_y_dps","gyro_z_dps"):
    if c not in df.columns:
        df[c] = 0.0

df = df.sort_values("timestamp").reset_index(drop=True)
numcols = df.select_dtypes(include=[np.number]).columns
df[numcols] = df[numcols].interpolate().fillna(0.0)

times = (df["timestamp"] - df["timestamp"].iloc[0]).dt.total_seconds().values
dt = np.diff(times, prepend=times[0])
if np.any(dt <= 0):
    pos = dt[dt > 0]
    dt[dt <= 0] = np.mean(pos) if len(pos) else 1.0

vel = df["velocity_m_s"].to_numpy(dtype=float)
alt = np.zeros(len(df))
for i in range(1, len(df)):
    alt[i] = alt[i-1] + vel[i] * dt[i]
alt = np.clip(alt, 0.0, 32000.0)

gyro_dps = df[["gyro_x_dps","gyro_y_dps","gyro_z_dps"]].to_numpy(dtype=float)
n = len(gyro_dps)
if n >= 7:
    win = SMOOTH_WINDOW if SMOOTH_WINDOW < n else (n // 2) * 2 + 1
    if win % 2 == 0: win -= 1
    if win < 3: win = 3
    try:
        gyro_smoothed = np.zeros_like(gyro_dps)
        for i in range(3):
            gyro_smoothed[:, i] = savgol_filter(gyro_dps[:, i], win, SMOOTH_POLYORDER)
    except Exception:
        gyro_smoothed = gyro_dps.copy()
else:
    gyro_smoothed = gyro_dps.copy()

gyro_rad = np.deg2rad(gyro_smoothed)
orientations = [R.identity()]
for i in range(1, len(df)):
    omega = gyro_rad[i] * dt[i]
    orientations.append(orientations[-1] * R.from_rotvec(omega))
rotations = np.array([r.as_matrix() for r in orientations])

acc_vec = df[["accel_x_m_s2","accel_y_m_s2","accel_z_m_s2"]].to_numpy(dtype=float)
acc_mag = np.linalg.norm(acc_vec, axis=1)
burst_idx = int(np.argmax(acc_mag))
tail_start = int(len(acc_mag) * 0.90)
impact_idx = tail_start + int(np.argmax(acc_mag[tail_start:])) if tail_start < len(acc_mag) else len(acc_mag)-1
descent_start_idx = min(len(df)-1, burst_idx + 1)
event_windows = {
    "ASCENT": (0, max(0, burst_idx-1)),
    "BURST": (max(0, burst_idx-2), min(len(df)-1, burst_idx+4)),
    "DESCENT": (descent_start_idx, max(descent_start_idx+1, impact_idx-1)),
    "IMPACT": (max(0, impact_idx-3), min(len(df)-1, impact_idx+4))
}

# use exact sample->frame mapping (one frame per telemetry row)
export_fps = int(max(1, round(1.0 / np.median(dt[np.where(dt > 0)]))))
if export_fps > 60:
    warnings.warn("Capping export FPS to 60 for encoder stability.")
    export_fps = 60
selected_frames = np.arange(len(df))
total_output_frames = len(selected_frames)

# ---------------- HELPERS: visuals ----------------
def altitude_to_color(h):
    a = np.clip(h / 30000.0, 0, 1)
    ground = np.array([0.03, 0.02, 0.015])  # near black for left background base
    mapped = None
    if a < 0.4:
        t = a / 0.4
        mapped = (1-t) * np.array([0.01,0.01,0.02]) + t * np.array([0.08,0.12,0.2])
    else:
        t = (a - 0.4) / 0.6
        mapped = (1-t) * np.array([0.08,0.12,0.2]) + t * np.array([0.02,0.03,0.06])
    return tuple(np.clip(mapped, 0, 1))

# build cube and compute face shading per-rotation
def cube_faces(size):
    L = size/2.0
    v = np.array([[-L,-L,-L],[ L,-L,-L],[ L, L,-L],[-L, L,-L],
                  [-L,-L, L],[ L,-L, L],[ L, L, L],[-L, L, L]])
    faces_idx = [[0,1,2,3],[4,5,6,7],[0,1,5,4],[2,3,7,6],[1,2,6,5],[0,3,7,4]]
    return v, faces_idx

def shade_faces(rotmat, faces_idx, verts, base_color, light_dir=np.array([0.3, 0.5, 1.0])):
    # compute rotated vertices
    rv = (rotmat @ verts.T).T
    face_colors = []
    for f in faces_idx:
        p0, p1, p2 = rv[f[0]], rv[f[1]], rv[f[2]]
        # normal
        normal = np.cross(p1-p0, p2-p0)
        norm = np.linalg.norm(normal)
        if norm == 0:
            nrm = np.array([0,0,1])
        else:
            nrm = normal / norm
        L = light_dir / np.linalg.norm(light_dir)
        lambert = np.clip(np.dot(nrm, L), 0.1, 1.0)  # keep some ambient
        face_col = np.clip(base_color * (0.5 + 0.5*lambert), 0, 1)
        face_colors.append(tuple(face_col))
    return rv, face_colors

# vertical rod coordinates (so the rod passes through cube center)
def rod_points(altitudes, length_scale=1.0):
    # map altitudes to z positions for the left view
    z = altitudes / (np.max(altitudes) + 1e-6) * 2.4  # normalized length
    x = np.zeros_like(z)
    y = -0.4 + 0.2  # minor offset so cube appears slightly right-of-center
    return x, np.full_like(z, y), z - 1.2  # center vertical

# ---------------- Figure setup ----------------
plt.style.use("dark_background")
fig = plt.figure(figsize=(FRAME_WIDTH/ DPI, FRAME_HEIGHT/ DPI), dpi=DPI)
# left: big 3d axes; right: chart image
from matplotlib.gridspec import GridSpec
gs = GridSpec(nrows=1, ncols=2, width_ratios=[2.0, 1.0], wspace=0.10, figure=fig)
ax3d = fig.add_subplot(gs[0], projection="3d")
ax3d.set_box_aspect((1,1,1))
ax3d.set_xticks([]); ax3d.set_yticks([]); ax3d.set_zticks([])
ax3d.set_xlim([-1.0, 1.0]); ax3d.set_ylim([-1.0, 1.0]); ax3d.set_zlim([-1.6, 1.2])

ax_chart = fig.add_subplot(gs[1])
ax_chart.axis("off")

# attempt to load chart image (svg -> raster via pillow or fallback)
chart_img = None
if os.path.exists(CHART_SVG):
    try:
        # pillow can open svg if system supports; otherwise fallback to leaving axis blank
        chart_img = Image.open(CHART_SVG).convert("RGBA")
    except Exception:
        try:
            # try cairosvg if installed to rasterize
            import cairosvg
            png_data = cairosvg.svg2png(url=CHART_SVG)
            from io import BytesIO
            chart_img = Image.open(BytesIO(png_data)).convert("RGBA")
        except Exception:
            chart_img = None

if chart_img is not None:
    ax_chart.imshow(chart_img)
    ax_chart.axis("off")
else:
    # fallback: recreate simplified telemetry chart on the right
    ax_chart.set_facecolor("#0F0F0F")
    ax_chart.text(0.5, 0.5, "mpu_chart.svg not found\n(placeholder)", ha="center", va="center", color="white", fontsize=14)

# 3D artist placeholders
verts, faces_idx = cube_faces(CUBE_SIZE)
poly = Poly3DCollection([], facecolors=[CUBE_BASE], edgecolors="#2a2a2a", linewidths=0.6)
ax3d.add_collection3d(poly)

# rod and trajectory points
traj_x, traj_y, traj_z = rod_points(alt)
# past and future visuals
past_line, = ax3d.plot([], [], [], lw=2.0, alpha=0.6, color="#1BBED6")
future_scat = ax3d.scatter([], [], [], s=26, alpha=0.45, color="#9AD6FF")

# rod representation: we place a thick dark line along the rod
rod_line, = ax3d.plot(traj_x, traj_y, traj_z, lw=18, solid_capstyle='round', alpha=0.95, color="#121417")

# trail and halo containers
trail_collection = Line3DCollection([[[0,0,0],[0,0,0]]], colors=[(0.2,0.6,1.0,0.12)], lw=2)
ax3d.add_collection3d(trail_collection)
halo_artist = None

# left overlay text/labels that match the concept (positions are figure-relative)
def draw_left_overlays():
    # large white labels with arrows pointing to target features
    fig.text(0.06, 0.72, "future\nvertical\npayload\ntrajectory", fontsize=26, color="white", va="center")
    fig.text(0.06, 0.45, "payload", fontsize=28, color="white", va="center")
    fig.text(0.06, 0.22, "passed\nvertical\npayload\ntrajectory", fontsize=26, color="white", va="center")
    # draw arrows (approximate)
    fig.annotate("", xy=(0.45, 0.75), xytext=(0.15, 0.75), xycoords='figure fraction', textcoords='figure fraction',
                 arrowprops=dict(arrowstyle="-|>", lw=3, color="white"))
    fig.annotate("", xy=(0.60, 0.52), xytext=(0.15, 0.52), xycoords='figure fraction', textcoords='figure fraction',
                 arrowprops=dict(arrowstyle="-|>", lw=3, color="white"))
    fig.annotate("", xy=(0.40, 0.28), xytext=(0.15, 0.28), xycoords='figure fraction', textcoords='figure fraction',
                 arrowprops=dict(arrowstyle="-|>", lw=3, color="white"))

draw_left_overlays()

# ---------------- EXPORT PREPARATION ----------------
writer = FFMpegWriter(fps=export_fps, metadata=dict(artist="BACAR-13 Replay"), codec=CODEC)
print(f"Exporting to {OUT_FILE} at {export_fps} fps, frames={total_output_frames}")
print("Ensure ffmpeg is installed and on PATH.")

# ---------------- FRAME LOOP (exact 1:1 mapping) ----------------
trail_buffer = np.zeros((TRAIL_LENGTH, 3))
impact_frame = -1

with writer.saving(fig, OUT_FILE, dpi=DPI):
    for out_i, frame in enumerate(selected_frames):
        # compute rotation
        Rm = rotations[frame]
        rv, facecols = shade_faces(Rm, faces_idx, verts, CUBE_BASE)
        poly.set_verts([[rv[idx] for idx in f] for f in faces_idx])
        poly.set_facecolor(facecols)

        # position cube slightly right-of-center along rod: cube center equals rod position at this sample
        cx, cy, cz = traj_x[frame], traj_y[frame], traj_z[frame]
        # we already rotated cube about origin; translate it to (cx, cy, cz)
        # Matplotlib Poly3DCollection stores vertices per-face; we rebuild faces with translation
        translated_faces = []
        for f in faces_idx:
            translated_faces.append([tuple(rv[idx] + np.array([cx, cy, cz])) for idx in f])
        poly.set_verts(translated_faces)

        # update rod thickness (simulate perspective by redrawing rod_line)
        rod_line.set_data(traj_x, traj_y)
        rod_line.set_3d_properties(traj_z)

        # past & future trajectory points: sample indices before/after current
        past_idx = np.where(np.arange(len(traj_z)) <= frame)[0]
        future_idx = np.where(np.arange(len(traj_z)) > frame)[0]
        past_line.set_data(traj_x[past_idx], traj_y[past_idx])
        past_line.set_3d_properties(traj_z[past_idx])
        # future: show every Nth point lightly to mimic dotted future arc
        if len(future_idx) > 0:
            step = max(1, len(future_idx)//24)
            future_line_points = future_idx[::step]
            future_scat._offsets3d = (traj_x[future_line_points], traj_y[future_line_points], traj_z[future_line_points])
        else:
            future_scat._offsets3d = ([], [], [])

        # trail (small acc vector trail)
        acc_w = Rm @ (acc_vec[frame] * ACC_SCALE)
        trail_buffer[:-1] = trail_buffer[1:]
        trail_buffer[-1] = acc_w
        segments = [[trail_buffer[i], trail_buffer[i+1]] for i in range(TRAIL_LENGTH-1)]
        trail_collection.set_segments(segments)

        # halo (subtle)
        if halo_artist is not None:
            try:
                halo_artist.remove()
            except Exception:
                pass
        halo_artist = None
        if alt[frame] < 12000:
            glow_strength = np.clip((12000.0 - alt[frame]) / 12000.0, 0.0, 1.0)
            halo_size = 1600.0 * (0.08 + 0.92 * glow_strength)
            halo_alpha = 0.02 + 0.35 * glow_strength
            halo_artist = ax3d.scatter([cx], [cy], [cz], s=halo_size, c=[(1.0, 0.9, 0.7, halo_alpha)], edgecolors='none')

        # background color
        bg = altitude_to_color(alt[frame])
        fig.patch.set_facecolor(bg)
        ax3d.set_facecolor(bg)

        # horizon thickening (affects arc alpha)
        horizon_strength = np.clip((5000.0 - alt[frame]) / 5000.0, 0.0, 1.0)
        # update horizon (slightly brighter when lower)
        # convert earlier horizon_line if exists
        # we set alpha using horizon_strength
        try:
            horizon_line.set_color((0.3 + 0.3*horizon_strength, 0.6 + 0.2*horizon_strength, 1.0, 0.2 + 0.6*horizon_strength))
            horizon_line.set_linewidth(5.0 * (1.0 + 0.6*horizon_strength))
        except Exception:
            pass

        # camera: place camera slightly angled so cube appears center-right
        elev = 14 + np.sin(frame * 0.02) * 2.5
        azim = 15 + frame * 0.12
        ax3d.view_init(elev=elev, azim=azim)

        # telemetry time markers on right axes (if chart is present, we can't move its internal lines;
        # but if it was absent we used a placeholder - otherwise we leave the svg as-is)
        # draw event banners
        fig.texts.clear()
        for name,(sidx,eidx) in event_windows.items():
            if sidx <= frame <= eidx:
                center = (sidx + eidx) / 2.0
                dist = abs(frame - center) / max(1.0, (eidx - sidx)/2.0)
                alpha = np.clip(1.0 - dist, 0.25, 1.0)
                draw_event_banner = lambda n,a: fig.text(0.04, 0.92, n, fontsize=20, color=(1,0.95,0.85,a),
                                                         bbox=dict(boxstyle="round,pad=0.6", facecolor=(0,0,0,0.6*a)))
                draw_event_banner(name, alpha)

        # HUD text (top-left small)
        fig.suptitle(f"BACAR-13 | t={times[frame]:.1f}s | Alt={alt[frame]:.0f} m", fontsize=14, color="white", y=0.96)

        # draw static overlay labels once (they're already drawn above)
        # grab frame
        writer.grab_frame(facecolor=fig.get_facecolor())

print("Export complete ->", OUT_FILE)
